title: RangersBot
theme: jekyll-theme-minimal
baseurl: /slack-rangersbot

links:
  - name: About
    href: '/slack-rangersbot/about/'
  - name: Issues
    href: '//github.com/chaoticweg/slack-rangersbot/issues'